-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpYjlAMnuG0u10S7b
ejeYA/DRCgpLdQsip4Sd0c3tZAmgCgYIKoZIzj0DAQehRANCAAQLwR380iSwtwr9
V8nGTSoYGZDnUhaMXB3hMlZHMNeUMA9h8NRFneLlAHXiHVhfMD6LRAz4qFH/IX5n
SFpxj/il
-----END PRIVATE KEY-----