name: myyearmystory
description: "Diário interativo mensal para registro de histórias, emoções e reflexões."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 🔐 Auth / Deep link
  webview_flutter: ^4.7.0

  # 📊 Gráficos e UI
  fl_chart: 1.1.1
  flutter_svg: 2.0.7
  smooth_page_indicator: 1.1.0

  # 🎙️ Áudio e gravação
  
  just_audio: 0.9.36
  path_provider: 2.1.3

  # 🌍 Localização e internacionalização
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.8
  intl: 0.20.2
  mask_text_input_formatter: ^2.0.0

  # ✨ Ícones e fontes
  cupertino_icons: 1.0.8
  google_fonts: 6.1.0
  phosphor_flutter: 2.1.0
  iconsax: 0.0.8
  

  # 🔐 Autenticação e banco de dados
  supabase_flutter: ^2.10.3
  shared_preferences: 2.3.2
  google_sign_in: 6.2.1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

  # 🔗 Navegação e links
  url_launcher: 6.2.5
  app_links: ^6.4.1

  # 🖼️ Imagens e arquivos
  image_picker: 1.1.2
  file_picker: 10.3.3

  # 📦 Informações do app
  package_info_plus: 9.0.0
  confetti: ^0.8.0
  flutter_animate: ^4.5.2

  # Notificações
  android_intent_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  flutter_launcher_icons: 0.13.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/imagens/logo.png
    - assets/imagens/logo_512px.png
    - assets/icons/google_icon.png