// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-EHwmFkQcqVJbXAzE50GGIDZwYZ5MYY',
    appId: '1:322091920984:android:567755d59f6b4677b5242d',
    messagingSenderId: '322091920984',
    projectId: 'myyearmystory',
    storageBucket: 'myyearmystory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1Vum_Jrs8p_fWBU26XODPxvD3Y00-HI',
    appId: '1:322091920984:ios:b7d668a8a85d5955b5242d',
    messagingSenderId: '322091920984',
    projectId: 'myyearmystory',
    storageBucket: 'myyearmystory.firebasestorage.app',
    androidClientId: '322091920984-tkn6jg309qur3dl22u3i7r9afet1v4cs.apps.googleusercontent.com',
    iosClientId: '322091920984-neqaqv51v49l5ljt4s6oi5pd317rgvh4.apps.googleusercontent.com',
    iosBundleId: 'com.myyear.myyearmystory',
  );
}
